import { ClipboardCheck, FileSignature, LockKeyhole, Stethoscope } from "lucide-react";
import { useEffect, useRef, useState, type ReactElement } from "react";
import { Link, useParams } from "react-router-dom";
import type { ClinicalNoteDraftInput, MedicationDecisionDraftInput, ReviewAllergyPayload, SignClinicalNoteAmendmentBody, VisitWorkspaceDto } from "../../shared/contracts";
import { useAuth } from "../auth/AuthProvider";
import { AllergyReviewDialog } from "../components/careflow/AllergyReviewDialog";
import { ClinicalNoteEditor } from "../components/careflow/ClinicalNoteEditor";
import { MedicationDecisionEditor } from "../components/careflow/MedicationDecisionEditor";
import { MedicationDecisionRevisionDialog } from "../components/careflow/MedicationDecisionRevisionDialog";
import { SignedClinicalEvidence } from "../components/careflow/SignedClinicalEvidence";
import { ActionButton, Card, PageHeader, SectionHeading, StatusBadge, TextAreaField } from "../components/careflow/ui";
import { createReviewAllergyAttempt, useReviewAllergy } from "../features/allergy";
import { createFinalizeAttempt, createSaveDraftAttempt, type ConsultationFormValue, useAmendClinicalNote, useFinalizeConsultation, useReviseMedicationDecision, useSaveConsultationDraft } from "../features/clinical";
import { useVisitWorkspace } from "../features/visit";
import { isApiError } from "../lib/api-error";
import { createCommandAttempt, type CommandAttempt } from "../lib/idempotency";
import { formatThaiDateTime } from "../lib/thai-date";

const blankNote: ClinicalNoteDraftInput = { subjective: "", objective: "", assessment: "", plan: "", diagnoses: [""] };
const blankValue: ConsultationFormValue = { note: blankNote, medicationDecision: { kind: "UNDECIDED" } };
function workspaceStamp(data: VisitWorkspaceDto) { return `${data.visit.revision}:${data.patient.revision}:${data.consultationDraft.note?.revision ?? 0}:${data.consultationDraft.medicationDecision?.revision ?? 0}`; }
function formValue(data: VisitWorkspaceDto): ConsultationFormValue {
  const note = data.consultationDraft.note;
  const decision = data.consultationDraft.medicationDecision;
  return {
    note: note ? { subjective: note.subjective, objective: note.objective, assessment: note.assessment, plan: note.plan, diagnoses: note.diagnoses.length ? note.diagnoses : [""] } : blankNote,
    medicationDecision: !decision || decision.kind === "UNDECIDED" ? { kind: "UNDECIDED" } : decision.kind === "NO_MEDICATION" ? { kind: "NO_MEDICATION", noMedicationReason: decision.noMedicationReason } : { kind: "ORDER", items: decision.items.map((item) => ({ medicationId: item.medication.id, medicationRevision: item.medication.revision, quantity: item.quantity, directionsTh: item.directionsTh })) },
  };
}
function decisionValid(value: MedicationDecisionDraftInput) { return value.kind === "ORDER" ? value.items.length > 0 && value.items.every((item) => item.quantity >= 1 && item.directionsTh.trim().length > 0) : value.kind === "NO_MEDICATION" && value.noMedicationReason.trim().length > 0; }
function message(error: unknown) { return isApiError(error) ? error.messageTh : "ไม่สามารถเชื่อมต่อระบบได้ กรุณาลองใหม่อีกครั้ง"; }

export function ConsultationScreen(): ReactElement {
  const { visitId = "" } = useParams(); const auth = useAuth(); const workspace = useVisitWorkspace(visitId);
  const save = useSaveConsultationDraft(); const finalize = useFinalizeConsultation(); const allergy = useReviewAllergy(); const amend = useAmendClinicalNote(); const revise = useReviseMedicationDecision();
  const [value, setValue] = useState<ConsultationFormValue>(blankValue); const [stamp, setStamp] = useState(""); const [conflict, setConflict] = useState(false); const [showAllergy, setShowAllergy] = useState(false); const [showConfirm, setShowConfirm] = useState(false); const [evidenceAction, setEvidenceAction] = useState<"amend" | "revise" | null>(null); const [amendment, setAmendment] = useState({ content: "", reason: "" });
  const saveAttempt = useRef<ReturnType<typeof createSaveDraftAttempt> | null>(null); const finalizeAttempt = useRef<ReturnType<typeof createFinalizeAttempt> | null>(null); const allergyAttempt = useRef<ReturnType<typeof createReviewAllergyAttempt> | null>(null); const allergyFingerprint = useRef(""); const amendmentAttempt = useRef<CommandAttempt<SignClinicalNoteAmendmentBody["payload"], SignClinicalNoteAmendmentBody["expectedRevisions"]> | null>(null); const confirmRef = useRef<HTMLElement>(null);
  useEffect(() => { if (!workspace.data) return; const next = workspaceStamp(workspace.data); if (next === stamp) return; queueMicrotask(() => { setValue(formValue(workspace.data!)); setStamp(next); setConflict(false); saveAttempt.current = null; finalizeAttempt.current = null; }); }, [stamp, workspace.data]);
  useEffect(() => { if (showConfirm) confirmRef.current?.focus(); }, [showConfirm]);
  if (workspace.isPending) return <div className="flow-page consultation-page"><PageHeader eyebrow="DOCTOR WORKSPACE" title="ห้องตรวจ" /><Card><div className="consultation-skeleton" /></Card></div>;
  if (!workspace.data) return <div className="flow-page consultation-page"><PageHeader eyebrow="DOCTOR WORKSPACE" title="ห้องตรวจ" /><Card><section className="workflow-blocked" role="alert"><LockKeyhole aria-hidden="true" /><p>{workspace.error ? message(workspace.error) : "ไม่พบข้อมูลห้องตรวจ"}</p></section></Card></div>;
  const data = workspace.data; const editable = data.allowedActions.includes("SAVE_DRAFT") && auth.session?.user.role === "doctor"; const validDecision = decisionValid(value.medicationDecision); const status = data.visit.status === "CONSULTING" ? { label: "กำลังตรวจ", tone: "active" as const } : { label: data.visit.status, tone: "waiting" as const };
  const saveDraft = () => { if (!validDecision) return; saveAttempt.current ??= createSaveDraftAttempt(data, value); save.mutate({ visitId: data.visit.id, attempt: saveAttempt.current }, { onError: (error) => { if (isApiError(error) && error.status === 409) { setConflict(true); saveAttempt.current = null; } }, onSuccess: () => { saveAttempt.current = null; } }); };
  const sign = () => { if (conflict || !validDecision) return; try { finalizeAttempt.current ??= createFinalizeAttempt(data); } catch { return; } finalize.mutate({ visitId: data.visit.id, attempt: finalizeAttempt.current }, { onError: (error) => { if (isApiError(error) && error.status === 409) { setConflict(true); finalizeAttempt.current = null; setShowConfirm(false); } }, onSuccess: () => { finalizeAttempt.current = null; setShowConfirm(false); } }); };
  const reviewAllergy = (payload: ReviewAllergyPayload) => { const next = { ...payload, visitId: data.visit.id }; const fingerprint = JSON.stringify(next); if (fingerprint !== allergyFingerprint.current) { allergyFingerprint.current = fingerprint; allergyAttempt.current = null; } allergyAttempt.current ??= createReviewAllergyAttempt(data, next); allergy.mutate({ workspace: data, attempt: allergyAttempt.current }, { onSuccess: () => { allergyAttempt.current = null; allergyFingerprint.current = ""; setShowAllergy(false); } }); };
  const changeValue = (next: ConsultationFormValue) => { setValue(next); saveAttempt.current = null; finalizeAttempt.current = null; };
  const submitAmendment = () => { if (!data.signedClinicalNote || !amendment.content.trim() || !amendment.reason.trim()) return; amendmentAttempt.current ??= createCommandAttempt({ amendment: data.amendments.length }, amendment); amend.mutate({ visitId: data.visit.id, noteId: data.signedClinicalNote.id, attempt: amendmentAttempt.current }, { onSuccess: () => { amendmentAttempt.current = null; setEvidenceAction(null); } }); };
  return <div className="flow-page consultation-page">
    <PageHeader eyebrow="DOCTOR WORKSPACE · CONSULTATION" title="ห้องตรวจผู้ป่วย" description="บันทึก Clinical Note และการตัดสินใจเรื่องยาในข้อมูลสังเคราะห์" />
    <div className="clinical-workspace-grid"><aside className="care-card consultation-patient-rail" aria-label="บริบทผู้ป่วย"><div className="patient-header"><div className="patient-header-copy"><strong>{data.patient.displayName}</strong><span>HN {data.patient.hn}</span></div><StatusBadge tone={status.tone}>{status.label}</StatusBadge></div><div className="allergy-summary"><span>ประวัติแพ้ยา</span><strong>{data.patientSnapshot.allergy.state}</strong><ActionButton type="button" variant="secondary" onClick={() => setShowAllergy(true)} disabled={!data.allowedActions.includes("REVIEW_ALLERGY")}>ทบทวนประวัติแพ้</ActionButton></div><Link className="care-button care-button-secondary" to="/queue">กลับคิวผู้ป่วย</Link></aside>
      <div className="consultation-clinical-content"><section className="care-card consultation-current-visit" aria-label="ข้อมูล Visit ปัจจุบัน"><SectionHeading icon={Stethoscope} title="ข้อมูล Visit ปัจจุบัน" description={`อาการสำคัญ: ${data.intake.chiefComplaint}`} /><div className="consultation-meta"><span>Visit {data.visit.id}</span><span>revision {data.visit.revision}</span><StatusBadge tone={status.tone}>{status.label}</StatusBadge></div><div className="vitals-summary"><span>อุณหภูมิ <strong>{data.intake.vitals.temperatureC ?? "—"}</strong></span><span>ชีพจร <strong>{data.intake.vitals.heartRateBpm ?? "—"}</strong></span><span>SpO₂ <strong>{data.intake.vitals.spo2Percent ?? "—"}</strong></span><span>เริ่มห้องตรวจ <strong>{data.visit.startedAt ? formatThaiDateTime(data.visit.startedAt) : "ยังไม่เริ่ม"}</strong></span></div><section className="clinical-evidence" aria-label="หลักฐานจาก Intake"><SectionHeading icon={ClipboardCheck} title="หลักฐานจาก Intake" description="ข้อมูลนี้มาจาก snapshot ที่บันทึกแล้ว" /><p>{data.intake.recordedBy.displayName} · {formatThaiDateTime(data.intake.recordedAt)}</p></section></section>
        {data.signedClinicalNote && data.medicationDecision ? <><SignedClinicalEvidence note={data.signedClinicalNote} decision={data.medicationDecision} amendments={data.amendments} onAmend={data.allowedActions.includes("AMEND_NOTE") ? () => setEvidenceAction("amend") : undefined} onRevise={data.allowedActions.includes("REVISE_MEDICATION_DECISION") ? () => setEvidenceAction("revise") : undefined} /><div className="signed-next-actions">{data.visit.status === "AWAITING_ORDER_REVISION" ? <strong>รอแก้ไขการตัดสินใจยา</strong> : <><span>การจัดยาและชำระเงินยังไม่พร้อมใน Pilot</span><ActionButton type="button" variant="secondary" disabled>ไปหน้าจัดยา (ยังไม่พร้อม)</ActionButton><ActionButton type="button" variant="secondary" disabled>ไปหน้าชำระเงิน (ยังไม่พร้อม)</ActionButton></>}</div></> : <section className="care-card consultation-note-panel" aria-label="Clinical Note"><SectionHeading icon={FileSignature} title="Clinical Note" description="บันทึกโดยแพทย์เท่านั้น" />{conflict ? <div role="alert" className="conflict-alert">ข้อมูลเวอร์ชันปัจจุบันเปลี่ยนแปลงแล้ว กรุณาโหลดข้อมูลล่าสุดก่อนลงนาม <ActionButton type="button" variant="secondary" onClick={() => void workspace.refetch()}>โหลดข้อมูลล่าสุด</ActionButton></div> : null}{save.error ? <p className="field-error" role="alert">{message(save.error)}</p> : null}{finalize.error ? <p className="field-error" role="alert">{message(finalize.error)}</p> : null}<ClinicalNoteEditor value={value.note} onChange={(note) => changeValue({ ...value, note })} disabled={!editable || save.isPending || finalize.isPending} /><SectionHeading title="การตัดสินใจเรื่องยา" description="ต้องเลือกคำสั่งยา หรือระบุว่าไม่สั่งยา" /><MedicationDecisionEditor value={value.medicationDecision} onChange={(medicationDecision) => changeValue({ ...value, medicationDecision })} disabled={!editable || save.isPending || finalize.isPending} />{!validDecision ? <p className="field-error">กรุณาระบุรายการยาและวิธีใช้ หรือเหตุผลที่ไม่สั่งยา</p> : null}<div className="consultation-actions"><ActionButton type="button" variant="secondary" onClick={saveDraft} disabled={!editable || save.isPending || !validDecision}>{save.isPending ? "กำลังบันทึก…" : "บันทึกร่าง"}</ActionButton><ActionButton type="button" onClick={() => setShowConfirm(true)} disabled={!editable || conflict || !validDecision || !data.consultationDraft.note || !data.consultationDraft.medicationDecision}>ลงนามและส่งต่อ</ActionButton></div></section>}</div></div>
    {showAllergy ? <AllergyReviewDialog allergy={data.patientSnapshot.allergy} onClose={() => setShowAllergy(false)} onSave={reviewAllergy} pending={allergy.isPending} /> : null}
    {showConfirm ? <div className="dialog-backdrop"><section className="care-card sign-dialog" role="dialog" aria-modal="true" aria-label="ยืนยันการลงนาม" ref={confirmRef} tabIndex={-1} onKeyDown={(event) => { if (event.key === "Escape") setShowConfirm(false); if (event.key === "Enter" && !event.shiftKey) sign(); }}><h2>ยืนยันการลงนาม</h2><p>การวินิจฉัย: {value.note.diagnoses.filter(Boolean).join(", ") || "ยังไม่ระบุ"}</p><p>การตัดสินใจยา: {value.medicationDecision.kind === "ORDER" ? "สั่งยา" : "ไม่สั่งยา"}</p><div className="dialog-actions"><ActionButton type="button" variant="secondary" onClick={() => setShowConfirm(false)} disabled={finalize.isPending}>ยกเลิก</ActionButton><ActionButton type="button" onClick={sign} disabled={finalize.isPending}>ยืนยันการลงนาม</ActionButton></div></section></div> : null}
    {evidenceAction === "amend" ? <div className="dialog-backdrop"><section className="care-card sign-dialog" role="dialog" aria-modal="true" aria-label="เพิ่มคำแก้ไข"><h2>เพิ่มคำแก้ไข</h2><TextAreaField label="รายละเอียด" value={amendment.content} onChange={(event) => { amendmentAttempt.current = null; setAmendment({ ...amendment, content: event.target.value }); }} disabled={amend.isPending} /><TextAreaField label="เหตุผล" value={amendment.reason} onChange={(event) => { amendmentAttempt.current = null; setAmendment({ ...amendment, reason: event.target.value }); }} disabled={amend.isPending} />{amend.error ? <p className="field-error">{message(amend.error)}</p> : null}<div className="dialog-actions"><ActionButton type="button" variant="secondary" onClick={() => setEvidenceAction(null)} disabled={amend.isPending}>ยกเลิก</ActionButton><ActionButton type="button" onClick={submitAmendment} disabled={amend.isPending || !amendment.content.trim() || !amendment.reason.trim()}>ลงนาม</ActionButton></div></section></div> : null}
    {evidenceAction === "revise" && data.medicationDecision ? <MedicationDecisionRevisionDialog decision={data.medicationDecision} expectedRevisions={{ visit: data.visit.revision, patient: data.patient.revision, medicationDecision: data.medicationDecision.version }} pending={revise.isPending} error={revise.error ? message(revise.error) : undefined} onCancel={() => setEvidenceAction(null)} onSubmit={(attempt) => revise.mutate({ visitId: data.visit.id, attempt }, { onSuccess: () => setEvidenceAction(null) })} /> : null}
  </div>;
}
