import { useState } from "react";
import type { AllergyAssessmentDto, ReviewAllergyPayload } from "../../../shared/contracts";
import { ActionButton, TextAreaField } from "./ui";

export function AllergyReviewDialog({ allergy, onClose, onSave, pending }: { allergy: AllergyAssessmentDto; onClose: () => void; onSave: (value: ReviewAllergyPayload) => void; pending: boolean }) {
  const [state, setState] = useState<ReviewAllergyPayload["state"]>(allergy.state); const [sourceText, setSourceText] = useState(allergy.sourceText ?? "ทบทวนข้อมูลแพ้ยา"); const [reason, setReason] = useState(allergy.reason ?? "ทบทวนก่อนการรักษา"); const [substance, setSubstance] = useState(allergy.items[0]?.substance ?? ""); const [reaction, setReaction] = useState(allergy.items[0]?.reaction ?? "");
  const submit = () => onSave({ visitId: "", state, sourceText, reason, items: state === "PRESENT" ? [{ substance, reaction, severity: allergy.items[0]?.severity ?? "UNKNOWN", note: null }] : [] });
  return <div className="dialog-backdrop" role="presentation"><section className="care-card allergy-dialog" role="dialog" aria-modal="true" aria-label="ทบทวนประวัติแพ้ยา"><h2>ทบทวนประวัติแพ้ยา</h2><div className="decision-choice">{(["UNKNOWN", "NONE_KNOWN", "PRESENT"] as const).map((option) => <ActionButton type="button" key={option} variant={state === option ? "primary" : "secondary"} onClick={() => setState(option)} disabled={pending}>{option}</ActionButton>)}</div>{state === "PRESENT" ? <><label className="field"><span className="field-label">สารที่แพ้</span><input className="care-input" value={substance} onChange={(event) => setSubstance(event.target.value)} /></label><label className="field"><span className="field-label">อาการแพ้</span><input className="care-input" value={reaction} onChange={(event) => setReaction(event.target.value)} /></label></> : null}<TextAreaField label="แหล่งข้อมูล" value={sourceText} onChange={(event) => setSourceText(event.target.value)} /><TextAreaField label="เหตุผลการทบทวน" value={reason} onChange={(event) => setReason(event.target.value)} /><div className="dialog-actions"><ActionButton type="button" variant="secondary" onClick={onClose} disabled={pending}>ยกเลิก</ActionButton><ActionButton type="button" onClick={submit} disabled={pending}>บันทึกการทบทวน</ActionButton></div></section></div>;
}
